from __future__ import annotations

from pathlib import Path
from typing import Any
import argparse

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss, roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from .round_win_dataset import (CATEGORICAL_ROUND_WIN_FEATURES, NUMERIC_ROUND_WIN_FEATURES,
                                ROUND_WIN_FEATURES, validate_round_win_dataset)
from .round_win_model import FEATURE_VERSION


DEFAULT_ARTIFACT_PATH = Path(__file__).with_name("artifacts") / "round_win_loadout.joblib"


def train_round_win_model(dataset: pd.DataFrame, *, artifact_path: str | Path = DEFAULT_ARTIFACT_PATH,
                          min_samples: int = 200) -> dict[str, Any]:
    validation = validate_round_win_dataset(dataset)
    clean = dataset.dropna(subset=["round_won"]).sort_values("game_start_millis")
    if not validation["valid"] or len(clean) < min_samples or clean["round_won"].nunique() < 2:
        return {"available": False, "reason": "round_win_dataset_insufficient", "validation": validation,
                "samples": len(clean), "feature_version": FEATURE_VERSION}
    split = max(1, min(len(clean) - 1, int(len(clean) * .8)))
    train, test = clean.iloc[:split], clean.iloc[split:]
    if train["round_won"].nunique() < 2:
        return {"available": False, "reason": "round_win_training_class_insufficient",
                "samples": len(clean), "feature_version": FEATURE_VERSION}
    preprocess = ColumnTransformer([
        ("numeric", Pipeline([("impute", SimpleImputer(strategy="median")), ("scale", StandardScaler())]), NUMERIC_ROUND_WIN_FEATURES),
        ("categorical", Pipeline([("impute", SimpleImputer(strategy="most_frequent")),
                                  ("onehot", OneHotEncoder(handle_unknown="ignore"))]), CATEGORICAL_ROUND_WIN_FEATURES),
    ])
    pipeline = Pipeline([("preprocess", preprocess),
                         ("model", LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42))])
    pipeline.fit(train[ROUND_WIN_FEATURES], train["round_won"].astype(int))
    probabilities = pipeline.predict_proba(test[ROUND_WIN_FEATURES])[:, 1] if len(test) else []
    metrics: dict[str, float | None] = {"roc_auc": None, "log_loss": None}
    if len(test) and test["round_won"].nunique() > 1:
        metrics = {"roc_auc": float(roc_auc_score(test["round_won"], probabilities)),
                   "log_loss": float(log_loss(test["round_won"], probabilities))}
    bundle = {"pipeline": pipeline, "features": ROUND_WIN_FEATURES, "feature_version": FEATURE_VERSION,
              "model_scope": "global_temporal", "confidence": .72, "metrics": metrics,
              "train_samples": len(train), "test_samples": len(test)}
    target = Path(artifact_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(bundle, target)
    return {"available": True, "artifact_path": str(target), "samples": len(clean),
            "train_samples": len(train), "test_samples": len(test), "metrics": metrics,
            "feature_version": FEATURE_VERSION}


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the optional pre-round loadout win model.")
    parser.add_argument("dataset", help="Parquet generated by the economy dataset builder.")
    parser.add_argument("--artifact", default=str(DEFAULT_ARTIFACT_PATH))
    parser.add_argument("--min-samples", type=int, default=200)
    args = parser.parse_args()
    from .round_win_dataset import build_round_win_dataset
    result = train_round_win_model(build_round_win_dataset(pd.read_parquet(args.dataset)),
                                   artifact_path=args.artifact, min_samples=args.min_samples)
    print(result)


if __name__ == "__main__":
    main()
